# Generated by Django 3.2.6 on 2021-08-15 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_gallery_project'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gallery',
            new_name='Photo',
        ),
    ]
